ch: enable nested chroot

diff --git a/.local/bin/ch b/.local/bin/ch
--- a/.local/bin/ch
+++ b/.local/bin/ch
@@ -2,10 +2,10 @@
 
 type schroot > /dev/null 2>&1 || exit
 
-if [ -f /etc/debian_chroot ]; then
-	echo "error: already inside '$(cat /etc/debian_chroot)'"
-	exit 1
-fi
+# if [ -f /etc/debian_chroot ]; then
+# 	echo "error: already inside '$(cat /etc/debian_chroot)'"
+# 	exit 1
+# fi
 
 if [ -z "$1" ]; then
 	echo "usage: $0 <session>"
