bump

diff --git a/.local/bin/ch b/.local/bin/ch
--- a/.local/bin/ch
+++ b/.local/bin/ch
@@ -3,21 +3,21 @@
 type schroot > /dev/null 2>&1 || exit
 
 if [ -z "$1" ]; then
-	echo "usage: ch <session>"
+	echo "usage: $0 <session>"
 	exit 1
 fi
 
-if schroot --list --all-sessions | grep -q chroot:$1; then
-	echo "session $1 not found"
+if schroot --list --all-sessions | grep -q chroot:"$1"; then
+	echo "error: session $1 not found"
 	exit 1
 fi
 
-if ls /var/lib/schroot/session | grep -q $1; then
-	if ! mount | grep -q /run/schroot/mount/$1; then
-		schroot --recover-session -c $1 > /dev/null
+if ls /var/lib/schroot/session | grep -q "$1"; then
+	if ! mount | grep -q /run/schroot/mount/"$1"; then
+		schroot --recover-session -c "$1" > /dev/null
 	fi
 else
-	schroot -b -n $1 -c $1 > /dev/null
+	schroot -b -n "$1" -c "$1" > /dev/null
 fi
 
-exec schroot -r -c $1
+exec schroot -r -c "$@"
